#! /bin/bash
set -e

[[ -x /usr/sbin/runsvdir-start ]] && /usr/sbin/runsvdir-start >/dev/null 2>&1 &

cd "$SOURCE_ROOT"
if [[ -n "$START_IN" ]]; then
  cd "$START_IN"
fi

if [[ -n "$BUILD_TARGET" ]]; then
  make -e "$BUILD_TARGET"
else
  make -e
fi

if [[ -n "$TESTS" ]]; then
  make "$TESTS"
fi
