#!/bin/bash

set -eo pipefail

if [[ -z $1 ]]; then
  echo "you must supply s3 key url"
  exit 1
fi

key_url="$1"
encrypted_key="/dev/shm/gpgsecret.key.enc"

aws s3 cp "$key_url" "$encrypted_key"
echo "Importing key..."
aws kms decrypt --ciphertext-blob "fileb://${encrypted_key}" \
    --query Plaintext --output text | \
  base64 -d | \
  gpg --allow-secret-key-import --import -
rm "$encrypted_key"
